### ISSUE TITLE
Does not compile with tcc 0.9.27

### ISSUE THREAD

**Issue by evolbug** [orangeduck/Cello#109]
Cannot compile it with the latest tcc version from http://repo.or.cz/tinycc.git mob branch.
```
tcc src/Table.c -c -I ./include -std=gnu99 -Wall -Wno-unused -g -ggdb -fdollars-in-identifiers -fPIC -DCELLO_NSTRACE -o obj/Table.o
src/Table.c:156: error: cannot cast 'struct Tuple' to 'void **'
make: *** [Makefile:125: obj/Table.o] Error 1
```

However, this page http://libcello.org/learn/best-improvements-of-cello-2.0 under `Portability` mentions that it can indeed be done
> [..] Cello can be compiled easily with all of the major compilers including `gcc`, `clang`, `cl.exe`, and `tcc` (on the development branch).

Has anything changed since or has `tcc` not been tested?

**Comment by orangeduck** [comment]
Just not tested recently. I guess some aspect of `tcc` has changed. It isn't immediately obvious why `tcc` is throwing that error so I'll have to dig a little deeper to see exactly what is going on.

**Comment by Pebaz** [comment]
Would love to see this fixed.  I am creating a project that needs to bundle TCC and use Cello.  I don't want to have to rely on the system compiler for each platform.

Attempted hello world example using TCC and failed:

```bash
tcc -fdollars-in-identifiers -I. example.c -L. -lCello -DCELLO_NSTRACE
```
```C
#define CELLO_NSTRACE
#include "Cello.h"

int main(int argc, char** argv)
{
	print("ASDF\n");
	return 0;
}
```
Compiles with GCC just fine but throws this error when used with TCC:
```
example.c:6: error: cannot cast 'struct Tuple' to 'void **'
```

**Comment by orangeduck** [comment]
Thanks I'll try to find some time to work out what has changed. Looks like it might be something in the macros used for variable argument functions...

**Comment by orangeduck** [comment]
I took a look. For some reason `tcc` is expanding macro arguments not really as expected. For example if I do:

```
var x = new(String);
```

Then it will throw that error, however if I do this:

```
var x = new_with(String, tuple());
```

However the definition of `new` is pretty much exactly that:

```
#define new(T, ...) ((struct T*)new_with(T, tuple(__VA_ARGS__)))
```

Even if you remove all the other stuff you still get the same error:

```
#define new(T, ...) new_with(T, tuple(__VA_ARGS__))
```

It seems to be failing to expand `tuple(__VA_ARGS__)` properly into `tuple()` when no arguments are passed to these variable argument macros.

Here I am not sure exactly what to do - I tried all my normal preprocessor hacks to try and get it to expand different but I couldn't find anything that works. Maybe it is worth reporting a bug with `tcc` and/or to try and dig into the source code to try and fix it.

Either way I have a feeling this is not Cello related and the same issue might exist in normal C programs compiled with `tcc`. I hope that helps!

Dan

**Comment by pierrotstudio1** [comment]
hello,
have you tried (GCC compatible ?)
#define new(T, ...) new_with(T, tuple(##__VA_ARGS__))

**Comment by KaruroChori** [comment]
Just a quick update for those interested in this issue in 2024. Many distributions are still delivering an older version of tcc which is incompatible. However the latest dev branch from https://repo.or.cz/tinycc.git seems to be working fine.

**Comment by pierrotstudio1** [comment]
Hello,
Thanks for the info. Indeed with tcc0928rc, I manage to compilethe CELLO library in 64 bits, on the other hand the compilation fails in 32 bitswith the error:C:/codeblocks/AppData/tcc/include/winapi/winnt.h:1478: error: invalid operand reference after %
Do you have any idea?
Thanks again

    Le jeudi 26 septembre 2024 à 19:39:32 UTC+2, KaruroChori ***@***.***> a écrit :  
 
 


Just a quick update for those interested in this issue in 2024. Many distributions are still delivering an older version of tcc which is incompatible. However the latest dev branch from https://repo.or.cz/tinycc.git seems to be working fine.
