### ISSUE TITLE
Failed to compile on GCC 8.1.0

### ISSUE THREAD

**Issue by Caikera** [orangeduck/Cello#139]
Environment: gcc version 8.1.0 (x86_64-posix-sjlj-rev0, Built by MinGW-W64 project)
Seems that the expanding method for macro has changed.
Get a series of error, such as:
`
D:/WorkSpace/C/cello_test/include/Cello.h:559:28: error: number of arguments doesn't match prototype
 #define tuple_in(_, ...) $(Tuple, (var[]){ __VA_ARGS__ })               
`
